# Generated by Django 4.0.4 on 2022-05-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='imagem',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
