# Generated by Django 4.0.4 on 2022-05-12 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0003_alter_arma_options_alter_municao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arma',
            options={},
        ),
        migrations.AddField(
            model_name='arma',
            name='objeto_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arma', to='armas.objeto'),
        ),
        migrations.AlterModelTable(
            name='arma',
            table=None,
        ),
    ]
