# Generated by Django 4.0.4 on 2022-05-12 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0004_alter_arma_options_arma_objeto_tipo_alter_arma_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arma',
            options={'ordering': ['marca_armamento']},
        ),
        migrations.AddField(
            model_name='municao',
            name='objeto_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municao', to='armas.objeto'),
        ),
        migrations.AlterModelTable(
            name='arma',
            table='arma',
        ),
    ]
